openapi: 3.0.0
info:
  title: Phonezone
  description: 
  version: 0.0.1
  contact:
    email: karandemo577@gmail.com
servers:
  - url: http://localhost:4000/api
    description: Development Server
  - url: https://iwebtrends.com/api
    description: Production Server

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /test:
    get:
      summary: A test route
      responses:
        '200':
          description: return an object
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
  #user routes
  /user/signup:
    put:
      summary: Signup route
      responses:
        '200':
          description: return an object
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string