name: Deploy on Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.11.0]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Set up environment variables
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_EXPIRY: ${{ secrets.JWT_EXPIRY }}
          PORT: ${{ secrets.PORT }}
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
          SMTP_MAIL_HOST: ${{ secrets.SMTP_MAIL_HOST }}
          SMTP_MAIL_PORT: ${{ secrets.SMTP_MAIL_PORT }}
          SMTP_MAIL_USERNAME: ${{ secrets.SMTP_MAIL_USERNAME }}
          SMTP_MAIL_PASSWORD: ${{ secrets.SMTP_MAIL_PASSWORD }}
          SMTP_MAIL_EMAIL: ${{ secrets.SMTP_MAIL_EMAIL }}
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          S3_REGION: ${{ secrets.S3_REGION }}
          RAZORPAY_KEY: ${{ secrets.RAZORPAY_KEY }}
          RAZORPAY_SECRET: ${{ secrets.RAZORPAY_SECRET }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        run: |
          echo "JWT_SECRET=${JWT_SECRET}" >> .env
          echo "JWT_EXPIRY=${JWT_EXPIRY}" >> .env
          echo "PORT=${PORT}" >> .env
          echo "MONGODB_URL=${MONGODB_URL}" >> .env
          echo "SMTP_MAIL_HOST=${SMTP_MAIL_HOST}" >> .env
          echo "SMTP_MAIL_PORT=${SMTP_MAIL_PORT}" >> .env
          echo "SMTP_MAIL_USERNAME=${SMTP_MAIL_USERNAME}" >> .env
          echo "SMTP_MAIL_PASSWORD=${SMTP_MAIL_PASSWORD}" >> .env
          echo "SMTP_MAIL_EMAIL=${SMTP_MAIL_EMAIL}" >> .env
          echo "S3_ACCESS_KEY=${S3_ACCESS_KEY}" >> .env
          echo "S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}" >> .env
          echo "S3_BUCKET_NAME=${S3_BUCKET_NAME}" >> .env
          echo "S3_REGION=${S3_REGION}" >> .env
          echo "RAZORPAY_KEY=${RAZORPAY_KEY}" >> .env
          echo "RAZORPAY_SECRET=${RAZORPAY_SECRET}" >> .env
          echo "GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}" >> .env

      # Add after install pm2 on EC2 instance
      - name: Restart Node.js application with PM2
        run: pm2 restart my_node_app